version: '3'

services:
  all:
    build: .
    container_name: uoj_all
    restart: always
    stdin_open: true
    tty: true
    cap_add:
      - SYS_PTRACE
    volumes:
      - mysql:/var/lib/mysql
      - data_main:/var/uoj_data
      - data_copy:/var/uoj_data_copy
      - ./web/app/views:/opt/uoj/web/app/views
      - ./web/app/controllers:/opt/uoj/web/app/controllers
      - ./web/app/locale:/opt/uoj/web/app/locale
      - ./web/public:/opt/uoj/web/public
      - ./web/app/models:/opt/uoj/web/app/models
      - var_log:/var/log
      - judger:/opt/uoj/judger
      - svn:/var/svn
    ports:
     - "8080:80"
     - "3690:3690"

volumes:
  mysql:
  data_main:
  data_copy:
  var_log:
  judger:
  svn:
